---
- hosts: bkplog
  tags: bkplog
  become: true
  roles:
    - roles/common
    - roles/bkpserver
    - roles/logserver
    - roles/alertmanager
    - roles/prometheus_node_exporter
    - roles/prometheus
    - roles/grafana

- hosts: fe
  tags: fe
  become: true
  roles:
    - roles/common
    - roles/prometheus_node_exporter
    - roles/nginx
    - roles/php
    - roles/mysqlrouter
    - roles/wordpress
    - roles/keepalived
    - roles/lsyncd
    - roles/bkpserver
    - roles/logclient

- hosts: db-master
  tags:
    - db
    - db-master
  become: true
  roles:
    - roles/common
    - roles/prometheus_node_exporter
    - roles/mysql-server
    - roles/bkpserver
    - roles/logclient

- hosts: db-slaves
  tags:
    - db
    - db-slaves
  become: true
  roles:
    - roles/common
    - roles/prometheus_node_exporter
    - roles/mysql-server
    - roles/bkpserver
    - roles/logclient
