---
- name: Download WordPress archive
  get_url: 
    url: https://ru.wordpress.org/wordpress-5.0.2-ru_RU.tar.gz
    dest: /tmp/wordpress.tar.gz
    validate_certs: no
  tags:
    - wp
    - wp-download

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html
    copy: no
  become: true
  tags:
    - wp
    - wp-unarchive

- name: Change ownership of wordpress directory
  file:
    path: /var/www/html/wordpress
    owner: nginx
    group: nginx
    recurse: yes
  become: true
  tags:
    - wp
    - wp-chown

- name: Copy sample config file
  copy:
    src: wp-config.php
    dest: /var/www/html/wordpress/wp-config.php
    owner: nginx
    group: nginx
    mode: 0644
  tags:
    - wp
    - wp-copy-sample

- name: Restore selinux context for files
  command: /sbin/restorecon -R /var/www/html
  become: true
  tags:
    - wp
    - wp-restorecon
