---
- name: Install epel repository
  yum:
    name: epel-release
    state: latest
  tags:
    - common
    - epel

- name: Install common packages
  yum:
    pkg: ['mc', 'nano', 'telnet', 'ntp', 'policycoreutils-python']
  tags:
    - common
    - cmn-packages

- name: Set timezone
  timezone:
    name: Europe/Moscow
  notify: restart cron

- name: Start the NTP service
  service:
    name: ntpd 
    state: started
    enabled: true
  tags:
    - common
    - cmn-start-ntp

- name: Start the firewalld service
  service:
    name: firewalld
    state: started
    enabled: true
  tags:
    - common
    - cmn-start-fwld

- name: Update hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  tags:
    - common
    - etc-hosts
