---

- name: Install web stack
  hosts: web
  become: true 
  gather_facts: false

  tasks:
  - name: Install docker requirements
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
      update_cache: true
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    tags:
      - docker
  
  - name: Add Docker s official GPG key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags:
      - docker

  - name: Verify that we have the key with the fingerprint
    ansible.builtin.apt_key:
      id: 0EBFCD88
      state: present
    tags:
      - docker
  
  - name: Set up the stable repository
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
      update_cache: true
    tags:
      - docker
  
  - name: Update apt packages
    ansible.builtin.apt:
      update_cache: true
    tags:
      - docker
  
  - name: Install docker
    ansible.builtin.apt:
      name: docker-ce
      state: present
      update_cache: true
    tags:
      - docker
  
  - name: Add remote "vagrant" user to "docker" group
    ansible.builtin.user:
      name: vagrant
      groups: 
        - "docker"
      append: true
    tags:
      - docker

  - name: Install docker-compose 
    ansible.builtin.get_url:
      url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 0777

  - name: Copy project
    ansible.builtin.copy:
      src: ../docker
      dest: /home/vagrant
      # directory_mode: true
      owner: vagrant
      group: vagrant
      mode: '0770'

  - name: reset ssh connection
    ansible.builtin.meta: reset_connection

  - name: Run container
    ansible.builtin.shell:
      cmd: "docker-compose -f docker-compose.yml up -d"
      chdir: /home/vagrant/docker
