---
- name: Get /etc/sysconfig/network-scripts/ifcfg-eth0 content
  command: /bin/cat /etc/sysconfig/network-scripts/ifcfg-eth0
  register: ifcfg_eth0_content

- name: Add disabled DEFROUTE if not set
  lineinfile:
    insertafter: EOF
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: "DEFROUTE=no"
  when: not ifcfg_eth0_content is search("DEFROUTE=")
  notify:
    - systemctl-restart-network

- name: Disable DEFROUTE
  replace:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: 'DEFROUTE=yes'
    replace: 'DEFROUTE=no'
  when: ifcfg_eth0_content is search("DEFROUTE=yes")
  notify:
    - systemctl-restart-network

- name: Get ifcfg-eth1 content
  command: /bin/cat /etc/sysconfig/network-scripts/ifcfg-eth1
  register: ifcfg_eth1_content

- name: Add enabled DEFROUTE if not set
  lineinfile:
    insertafter: EOF
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1
    line: "DEFROUTE=yes"
  when: not ifcfg_eth1_content is search("DEFROUTE=")
  notify:
    - systemctl-restart-network

- name: Enable DEFROUTE
  replace:
    path: /etc/sysconfig/network-scripts/ifcfg-eth1
    regexp: 'DEFROUTE=yes'
    replace: 'DEFROUTE=no'
  when: ifcfg_eth1_content is search("DEFROUTE=yes")
  notify:
    - systemctl-restart-network
