---
- name: Install remi php repository
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Enable remi 7.2 repository
  yum_repository:
    name: remi-php72
    description: Remi's PHP 7.2 RPM repository for Enterprise Linux 7 - $basearch
    file: remi-php72
    mirrorlist: http://cdn.remirepo.net/enterprise/7/php72/mirror
    enabled: true
    gpgcheck: yes
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-remi
  tags:
    - enable-php-repo

- name: Install PHP packages
  yum: pkg={{ item }}
  with_items:
    - php
    - php-gd
    - php-fpm
    - php-mysql
    - php-pear
    - php-xml
    - php-common
  tags:
    - php-packages

- name: Update php-configuration file
  template:
    src: php.ini.j2
    dest: /etc/php.ini
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm
  tags:
    - php-configuration
    - php-ini

- name: Update www.conf php-configuration file
  template:
    src: php-fpm.d/www.conf.j2
    dest: /etc/php-fpm.d/www.conf
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm
  tags:
    - php-configuration
    - php-conf

- name: Enable php-fpm service
  systemd:
    name: php-fpm
    enabled: true
  tags:
    - php-fpm-systemd-enable

- name: Start php-fpm service
  systemd:
    name: php-fpm
    state: started
  tags:
    - php-fpm-systemd-start
