Vagrant.configure("2") do |config|
  config.vm.hostname = "monitoring"
  config.vm.box = "centos/7"
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 9090, host: 9090

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yml"
  end
end
