---
- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart audit
  # for some reason auditd is not correctly restarted with "service" module
  command: service auditd restart
...
