# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|

  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/provision.yml"
      ansible.host_key_checking = "false"
   end

   config.vm.define "web" do |vmconfig| 
    vmconfig.vm.box = 'ubuntu/focal64'
    vmconfig.vm.hostname = 'web'

    vmconfig.vm.network "forwarded_port", guest: 8081, host: 8081
    vmconfig.vm.network "forwarded_port", guest: 8082, host: 8082
    vmconfig.vm.network "forwarded_port", guest: 8083, host: 8083
    vmconfig.vm.provider "virtualbox" do |vbx|
     vbx.memory = "2048"
     vbx.cpus = "2"
     vbx.customize ["modifyvm", :id, '--audio', 'none']
    end
   end

end