- name: OSPF
  hosts: all
  become: yes
  vars_files:
    - defaults/main.yml
  tasks:
  - name: install base tools
    apt:
      name:
        - vim
        - traceroute
        - tcpdump
        - net-tools
      state: present
      update_cache: true

#Отключаем UFW и удаляем его из автозагрузки
- name: disable ufw service
  service:
    name: ufw
    state: stopped
    enabled: false

# Добавляем gpg-key репозитория
- name: add gpg frrouting.org
  apt_key:
    url: "https://deb.frrouting.org/frr/keys.asc"
    state: present

# Добавляем репозиторий https://deb.frrouting.org/frr
- name: add frr repo
  apt_repository:
    repo: 'deb https://deb.frrouting.org/frr {{ ansible_distribution_release }} frr-stable'
    state: present

# Обновляем пакеты и устанавливаем FRR
- name: install FRR packages
  apt:
    name: 
      - frr
      - frr-pythontools
    state: present
    update_cache: true

# Включаем маршрутизацию транзитных пакетов
- name: set up forward packages across routers
  sysctl:
    name: net.ipv4.conf.all.forwarding
    value: '1'
    state: present

- name: Switch on ospfd daemon at frr
  ansible.builtin.lineinfile:
    path: /etc/frr/daemons
    regexp: "ospfd=no"
    line: ospfd=yes
    owner: frr
    group: frr
    mode: "0640"

- name: Switch on zebra daemon at frr
  ansible.builtin.lineinfile:
    path: /etc/frr/daemons
    regexp: "zebra=no"
    line: zebra=yes
    owner: frr
    group: frr
    mode: "0640"

# Перезапускам FRR и добавляем в автозагрузку
- name: restart FRR
  service:
    name: frr
    state: restarted
    enabled: true

# Отключаем запрет ассиметричного роутинга 
- name: set up asynchronous routing
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: '0'
    state: present

# Делаем интерфейс enp0s8 в router1 «дорогим» 
- name: Switch on ospfd daemon at frr
  ansible.builtin.lineinfile:
    path: /etc/frr/daemons
    regexp: "ospfd=no"
    line: ospfd=yes
    owner: frr
    group: frr
    mode: "0640"
  tags:
    - setup_ospf

- name: Switch on zebra daemon at frr
  ansible.builtin.lineinfile:
    path: /etc/frr/daemons
    regexp: "zebra=no"
    line: zebra=yes
    owner: frr
    group: frr
    mode: "0640"
  tags:
    - setup_ospf

# Применяем настройки
- name: restart FRR
  service:
    name: frr
    state: restarted
    enabled: true
  tags:
    - setup_ospf
