---
- name: Get /etc/sysctl.conf
  command: /bin/cat /etc/sysctl.conf
  register: sysctl_conf_content

- name: Add forwarding if it doesn't exist
  lineinfile:
    insertafter: EOF
    dest: /etc/sysctl.conf
    line: "net.ipv4.conf.all.forwarding = 1"
  when: not sysctl_conf_content is search("net.ipv4.conf.all.forwarding")
  notify:
    - systemctl-restart-network

- name: Enable forwarding
  replace:
    path: /etc/sysctl.conf
    regexp: 'net.ipv4.conf.all.forwarding = 0'
    replace: 'net.ipv4.conf.all.forwarding = 1'
  when: not sysctl_conf_content is search("net.ipv4.conf.all.forwarding = 0")
  notify:
    - systemctl-restart-network
