# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :"kernel-update" => {
        :box_name => "centos/stream8",
        :box_version => "20210210.0",
        :cpus => 2,
        :memory => 2048,
        :ip_addr => '192.168.56.10'
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.box_version = boxconfig[:box_version]
        box.vm.host_name = boxname.to_s

        #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

        box.vm.network "private_network", ip: boxconfig[:ip_addr]

        box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "1024"]
        end

        box.vm.provider "virtualbox" do |v|
          v.memory = boxconfig[:memory]
          v.cpus = boxconfig[:cpus]
        end
    end
  end
end

