---
- name: Create backup user
  user:
    name: bkp
    password: '$6$CrYpt0$mi.Pu2ghRvOCAMfPk8KSvJemc9cboVDHvKSXr8.Q48tGvGtf5ZFZWAWr9E/Scj6PB56tZHc81rnkYbf04e1r/0'
    state: present
    shell: /bin/bash
  tags:
    - backup

- name: Create .ssh directory for bkp user
  file:
    path: /home/bkp/.ssh
    state: directory
    owner: bkp
    group: bkp
    mode: 0700
  tags:
    - backup

- name: Copy private key
  copy:
    src: id_rsa
    dest: /root/.ssh/id_rsa
    owner: root
    group: root
    mode: 0600
  when: ansible_hostname == "bkplog"
  tags:
    - backup

- name: Edit authorized_keys file
  authorized_key:
    user: bkp
    state: present
    key: "{{ lookup('file', 'roles/bkpserver/files/id_rsa.pub') }}"
  tags:
    - backup

- name: Add backing up wordpress dirictory to cron
  cron:
    name: bkp-wp-dir
    minute: '*/10'
    user: root
    job: '/bin/tar cfz /home/bkp/wp.tar.gz /var/www/html/wordpress/'
    cron_file: wp-cron
  when: ansible_hostname == "fe1"
  tags:
    - backup
    - backup-cron

- name: Add backing up wordpress db to cron
  cron:
    name: bkp-wp-db
    minute: '*/10'
    user: root
    job: '/bin/mysqldump --single-transaction --set-gtid-purged=OFF wordpress > /home/bkp/wp.sql'
    cron_file: wp-cron
  when: ansible_hostname == "db1"
  tags:
    - backup
    - backup-cron

- name: Add copying of db backup to bkplog host
  cron:
    name: bkp-wp-db
    minute: '*/10'
    user: root
    job: '/bin/scp bkp@db1:wp.sql /home/bkp/backup/'
    cron_file: wp-cron
  when: ansible_hostname == "bkplog"
  tags:
    - backup
    - backup-cron

- name: Add copying of wordpress directory backup to bkplog host
  cron:
    name: bkp-wp-dir
    minute: '*/10'
    user: root
    job: '/bin/scp bkp@fe1:wp.tar.gz /home/bkp/backup/'
    cron_file: wp-cron
  when: ansible_hostname == "bkplog"
  tags:
    - backup
    - backup-cron
