---
- name: Copy resolv.conf to the clients
  ansible.builtin.copy:
    src: client-resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644

- name: Make /etc/resolv.conf immutable
  ansible.builtin.file:
    path: /etc/resolv.conf
    attributes: +i

- name: Copy rndc
  ansible.builtin.copy:
    src: rndc.conf
    dest: /home/vagrant/rndc.conf
    owner: vagrant
    group: vagrant
    mode: 0644

- name: Copy motd to clients
  ansible.builtin.copy:
    src: client-motd
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
