# tasks file for logserver
---
- name: Create /var/log/remote directory
  file:
    path: /var/log/remote
    state: directory
    mode: 0755
    owner: root
    group: root
  notify: restart rsyslog
  tags:
    - logserver
    - rsyslog-create-dir

- name: Update /etc/rsyslog.conf file
  template:
    src: etc/rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: 0644
  notify: restart rsyslog
  tags:
    - logserver
    - rsyslog-configuration

- name: Open firewalld for syslog
  firewalld:
    service: syslog
    zone: public
    permanent: yes
    state: enabled
  notify: restart firewalld
  tags:
    - logserver
    - logserver-firewalld
