---
- name: Create group borg
  group:
    name: borg
    state: present

- name: Add the user borg
  ansible.builtin.user:
    name: borg
    shell: /bin/bash
    home: /home/borg
    group: borg
    password: '$6$mysecretsalt$/7eyKUjo3oSPuEf160CYj4Zq1vxMPTkQAZ1mhPs5DVzANyU1dBH7X4z64tsUwiUuqgYpDdMsGZZ9XYkrcTQ2u.'

- name: Create ssh directory
  ansible.builtin.file:
    path: /home/borg/.ssh
    state: directory
    mode: 0700
    owner: borg
    group: borg

# - name: Create authorized_keys directory
#   ansible.builtin.file:
#     path: /home/borg/.ssh/authorized_keys
#     state: directory
#     mode: 0600
#     owner: borg
#     group: borg

- name: Copy ssh key to server
  ansible.builtin.template:
    src: /tmp/id_rsa.pub
    dest: /home/borg/.ssh/authorized_keys 
    owner: borg
    group: borg
    mode: 0600

- name: Create backup directory
  ansible.builtin.file:
    path: /var/backup
    state: directory

- name: Create a ext4 filesystem on /dev/sdb
  community.general.filesystem:
    fstype: ext4
    dev: /dev/sdb

- name: Mount and bind volume
  ansible.posix.mount:
    path: /var/backup
    src: /dev/sdb
    opts: rw,auto
    fstype: ext4
    state: mounted

- name: Remove lost+found directory
  ansible.builtin.file:
    path: /var/backup/lost+found
    state: absent

- name: Create backup directory
  ansible.builtin.file:
    path: /var/backup
    state: directory
    recurse: true
    owner: borg
    group: borg
    mode: 0770
